config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  resources :songs
  resources :search

end

app/models/concerns/index_setup.rb
module IndexSetup
  extend ActiveSupport::Concern
  
  included do
  end

  module ClassMethods
    def fetch_all
      uri = Addressable::URI.parse("http://stage48.net/studio48/lyricsindex_akb48.html")
      doc = Nokogiri::HTML(open("http://stage48.net/studio48/lyricsindex_akb48.html"))

      doc.search(".two-columns .column .content ul p").each do |section|
        section.inner_html.split("<br>").each do |song|
          song_node = Nokogiri::HTML(song)

          if song_link = song_node.at("a")
            song_url = uri + song_link["href"]
            song_slug = song_link.text.parameterize
            fetch_one(song_slug, song_url)
          end
        end
      end
    end

    def fetch_one(slug, url)
      Song.find_or_create_by(slug: slug, path: url.basename).tap do |song|
        doc = Nokogiri::HTML(open(url))
        
        # [0] => kana, [1] => romaji, [2] => english
        song_names = doc.search(".post.greenbox .title").text.split("|").map(&:strip)
        lyrics = doc.search(".two-columns .column")  

        song.update_attributes({
          name_jp: song_names[0],
          lyric_jp: ((lyrics[0].at("ul").text.strip.lines.map(&:strip).join("\n")) rescue nil),

          name_romaji: song_names[1],
          lyric_romaji: ((lyrics[1].at("ul").text.strip.lines.map(&:strip).join("\n")) rescue nil),

          name_en: song_names[2],
          lyric_en: ((lyrics[2].at("ul").text.strip.lines.map(&:strip).join("\n")) rescue nil),
        })
      end
    end

    def create_index
      self.__elasticsearch__.create_index! force: true
    end
  end
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern
  
  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    settings index: { analysis: { analyzer: { default: { type: "kuromoji" }}} } do
      mappings dynamic: 'false' do
        indexes :name_jp, analyzer: 'kuromoji'
        indexes :lyric_jp, analyzer: 'kuromoji'
      end
    end
  end
end

app/models/song.rb
require "open-uri"
require "addressable/uri"

class Song < ActiveRecord::Base
  include Searchable
  include IndexSetup

  def highlighted_lyrics(level)
    return lyric_jp if vocabs_of_level(level).count == 0

    query = vocabs_of_level(level).map(&:text).join(" ")
    
    response = Song.search({
      query: {
        filtered: {
          filter: {
            ids: {
              values: [id]
            }
          },
          query: {
            match: {
              _all: query
            }
          }
        }
      },
      highlight: {
        fields: {
          lyric_jp: {
            number_of_fragments: 0
          },
          name_jp: {}
        }
      }
    })

    response.first.highlight.lyric_jp[0]
  end

  def vocabs_of_level(level)
    Vocabulary.of_level(level).where(id: vocab_ids)
  end
end

app/models/vocabulary.rb
require "csv"

class Vocabulary < ActiveRecord::Base
  scope :of_level, -> (level) { where(level: level) }

  def text
    kanji || furigana
  end

  def matching_doc
    @matching_doc ||= Song.search(query: {match: {_all: text}}, size: 1000, fields: ["id"])
  end

  class << self
    def import
      delete_all

      csv_path = Rails.root.join("lib", "data", "jlpt_all_vocab.csv")

      CSV.foreach(csv_path, headers: :first_row) do |row|
        create({
          kanji: row["Kanji"],
          furigana: row["Furigana"],
          meaning: row["Meaning"],
          level: row["Level"]
        })
      end
    end

    def reset_occurrences
      Song.find_each do |song|
        song.update_attribute(:vocab_ids,[])
      end

      Vocabulary.find_each do |vocab|
        vocab.update_attribute(:song_ids,[])
      end
    end

    def build_occurrences
      reset_occurrences

      find_each do |vocab|
        response = Song.search(query: {match: {_all: vocab.text}}, size: 1000, fields: ["id"])

        vocab.song_ids = vocab.matching_doc.records.pluck(:id)
        vocab.save

        Song.where(id: vocab.song_ids).find_each do |song|
          song.vocab_ids = song.vocab_ids + [vocab.id]
          song.save
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:q]
      @response = Song.search(query: {match: {lyric_jp: params[:q]}}, highlight: { fields: { lyric_jp: {}} },).page(params[:page]).per(100)
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def show
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Minna no AKB48</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">


    <!-- Custom styles for this template -->
    <!-- <link href="navbar.css" rel="stylesheet"> -->

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Minna no AKB48!", root_path, class: "navbar-brand" %>
          </div>
          <div class="navbar-collapse collapse">
            <%= form_tag("/search", method: :get, class: "navbar-form navbar-left", role: "Search") do %>
              <div class="form-group">
                <%= text_field_tag "q", params[:q], class: "form-control", placeholder: "Search" %>
              </div>
              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            <% end %>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/search/index.html.erb
<% if params[:q] %>
  <h2>Search Result:</h2>
  <% @response.records.each_with_hit do |song, result| %>
  <div class="row result">
    <div class="col-lg-12">
      <h3>
        <%= result.name_jp %>
        <% %w{N5 N4 N3 N2 N1}.each do |level| %>
          <span class="song-link"><%= link_to level, song_path(song, level: level) %></span>
        <% end %>
      </h3>
      <p><%= raw result.highlight.lyric_jp[0] %></p>
    </div>
  </div>
  <% end %>

  <% if @response.empty? %>
  <h5>no matching song!</h5>
  <% end %>
<% end %>

app/views/songs/show.html.erb
<h2><%= @song.name_jp %></h2>
<h5>
  <% %w{N5 N4 N3 N2 N1}.each do |level| %>
    <span class="song-link"><%= link_to level, song_path(@song, level: level) %></span>
  <% end %>
</h5>
<div class="row result">
  <div class="col-lg-12">
    <%= raw simple_format(@song.highlighted_lyrics(params[:level])) %>
  </div>
</div>